"""message

Revision ID: 048c0850dbdf
Revises: 2eb591aa71d5
Create Date: 2022-07-24 21:01:10.411658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048c0850dbdf'
down_revision = '2eb591aa71d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
