"""message

Revision ID: 2eb591aa71d5
Revises: b23cf4294c9a
Create Date: 2022-07-24 20:54:46.344088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb591aa71d5'
down_revision = 'b23cf4294c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('last_dispensed_ticket', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'last_dispensed_ticket')
    # ### end Alembic commands ###
