"""message

Revision ID: b23cf4294c9a
Revises: bea4a45c7b85
Create Date: 2022-07-06 09:16:18.332983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cf4294c9a'
down_revision = 'bea4a45c7b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('missed_tickets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'missed_tickets')
    # ### end Alembic commands ###
