"""message

Revision ID: bea4a45c7b85
Revises: c12a23b5219e
Create Date: 2022-07-06 08:13:14.715440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea4a45c7b85'
down_revision = 'c12a23b5219e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('tickets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'tickets')
    # ### end Alembic commands ###
