"""message

Revision ID: c12a23b5219e
Revises: 
Create Date: 2022-06-21 23:28:37.930979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12a23b5219e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last', sa.DateTime(), nullable=True),
    sa.Column('sub1', sa.String(), nullable=True),
    sa.Column('sub2', sa.String(), nullable=True),
    sa.Column('sub3', sa.String(), nullable=True),
    sa.Column('sub4', sa.String(), nullable=True),
    sa.Column('sub5', sa.String(), nullable=True),
    sa.Column('sub6', sa.String(), nullable=True),
    sa.Column('sub7', sa.String(), nullable=True),
    sa.Column('sub8', sa.String(), nullable=True),
    sa.Column('sub9', sa.String(), nullable=True),
    sa.Column('sub10', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('s1', sa.Integer(), nullable=True),
    sa.Column('s2', sa.Integer(), nullable=True),
    sa.Column('s3', sa.Integer(), nullable=True),
    sa.Column('s4', sa.Integer(), nullable=True),
    sa.Column('s5', sa.Integer(), nullable=True),
    sa.Column('s6', sa.Integer(), nullable=True),
    sa.Column('s7', sa.Integer(), nullable=True),
    sa.Column('s8', sa.Integer(), nullable=True),
    sa.Column('s9', sa.Integer(), nullable=True),
    sa.Column('s10', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['s1'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s10'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s2'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s3'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s4'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s5'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s6'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s7'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s8'], ['service.id'], ),
    sa.ForeignKeyConstraint(['s9'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service1', sa.Integer(), nullable=True),
    sa.Column('service2', sa.Integer(), nullable=True),
    sa.Column('service3', sa.Integer(), nullable=True),
    sa.Column('service4', sa.Integer(), nullable=True),
    sa.Column('service5', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service1'], ['service.id'], ),
    sa.ForeignKeyConstraint(['service2'], ['service.id'], ),
    sa.ForeignKeyConstraint(['service3'], ['service.id'], ),
    sa.ForeignKeyConstraint(['service4'], ['service.id'], ),
    sa.ForeignKeyConstraint(['service5'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceid', sa.Integer(), nullable=True),
    sa.Column('servicename', sa.String(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('wait', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serviceid'], ['service.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('user')
    op.drop_table('chain')
    op.drop_table('service')
    # ### end Alembic commands ###
